import { ConfigPreset } from '@/types/preset';

export const eslintPresets: ConfigPreset[] = [
  {
    id: 'official',
    name: '공식 기본값',
    description: 'ESLint 공식 권장 설정입니다',
    prettierRules: {},
    eslintRules: {
      'indent': ['error', 2],
      'quotes': ['error', 'single'],
      'semi': ['error', 'always'],
      'comma-dangle': ['error', 'always-multiline'],
      'no-console': 'warn',
      'no-unused-vars': 'warn',
      'no-undef': 'error',
      'eqeqeq': 'error',
      'curly': 'error',
      'brace-style': ['error', '1tbs'],
      'arrow-parens': ['error', 'always'],
      'prefer-const': 'error',
      'no-var': 'error',
    },
    parserOptions: {
      ecmaVersion: 2023,
      sourceType: 'module',
    },
  },
  {
    id: 'airbnb',
    name: 'Airbnb',
    description: 'Airbnb JavaScript Style Guide 기반 ESLint 설정입니다',
    prettierRules: {},
    eslintRules: {
      'indent': ['error', 2],
      'quotes': ['error', 'single'],
      'semi': ['error', 'always'],
      'comma-dangle': ['error', 'always-multiline'],
      'no-console': 'error',
      'no-unused-vars': 'error',
      'no-undef': 'error',
      'eqeqeq': 'error',
      'curly': 'error',
      'brace-style': ['error', '1tbs'],
      'arrow-parens': ['error', 'always'],
      'prefer-const': 'error',
      'no-var': 'error',
    },
    parserOptions: {
      ecmaVersion: 2023,
      sourceType: 'module',
      ecmaFeatures: { jsx: true },
    },
  },
  {
    id: 'standard',
    name: 'Standard',
    description: 'Standard JS ESLint 설정입니다 (세미콜론 없음)',
    prettierRules: {},
    eslintRules: {
      'indent': ['error', 2],
      'quotes': ['error', 'single'],
      'semi': ['error', 'never'],
      'comma-dangle': ['error', 'never'],
      'no-console': 'warn',
      'no-unused-vars': 'warn',
      'no-undef': 'error',
      'eqeqeq': 'error',
      'curly': 'error',
      'brace-style': ['error', '1tbs'],
      'arrow-parens': ['error', 'as-needed'],
      'prefer-const': 'error',
      'no-var': 'error',
    },
    parserOptions: {
      ecmaVersion: 2023,
      sourceType: 'module',
    },
  },
];

export const defaultPreset = eslintPresets[0];
