import { ConfigPreset } from '@/types/preset';

export const prettierPresets: ConfigPreset[] = [
  {
    id: 'official',
    name: '공식 기본값',
    description: 'Prettier 공식 권장 설정입니다',
    prettierRules: {
      printWidth: 80,
      tabWidth: 2,
      useTabs: false,
      semi: true,
      singleQuote: false,
      quoteProps: 'as-needed',
      jsxSingleQuote: false,
      trailingComma: 'es5',
      bracketSpacing: true,
      bracketSameLine: false,
      arrowParens: 'always',
      proseWrap: 'preserve',
      htmlWhitespaceSensitivity: 'css',
      vueIndentScriptAndStyle: false,
      endOfLine: 'lf',
      embeddedLanguageFormatting: 'auto',
      singleAttributePerLine: false,
    },
    eslintRules: {},
  },
  {
    id: 'airbnb',
    name: 'Airbnb',
    description: 'Airbnb JavaScript Style Guide 기반 설정입니다',
    prettierRules: {
      printWidth: 100,
      tabWidth: 2,
      useTabs: false,
      semi: true,
      singleQuote: true,
      quoteProps: 'as-needed',
      jsxSingleQuote: false,
      trailingComma: 'all',
      bracketSpacing: true,
      bracketSameLine: false,
      arrowParens: 'always',
      proseWrap: 'preserve',
      htmlWhitespaceSensitivity: 'css',
      vueIndentScriptAndStyle: false,
      endOfLine: 'lf',
      embeddedLanguageFormatting: 'auto',
      singleAttributePerLine: false,
    },
    eslintRules: {},
  },
  {
    id: 'standard',
    name: 'Standard',
    description: 'Standard JS (세미콜론 없음) 스타일입니다',
    prettierRules: {
      printWidth: 80,
      tabWidth: 2,
      useTabs: false,
      semi: false,
      singleQuote: true,
      quoteProps: 'as-needed',
      jsxSingleQuote: false,
      trailingComma: 'none',
      bracketSpacing: true,
      bracketSameLine: false,
      arrowParens: 'avoid',
      proseWrap: 'preserve',
      htmlWhitespaceSensitivity: 'css',
      vueIndentScriptAndStyle: false,
      endOfLine: 'lf',
      embeddedLanguageFormatting: 'auto',
      singleAttributePerLine: false,
    },
    eslintRules: {},
  },
];

export const defaultPreset = prettierPresets[0];
